listener 1883
allow_anonymous false
password_file /mosquitto/config/passwd
persistence true
persistence_location /mosquitto/data/
# Crear el usuario:  docker compose exec mosquitto mosquitto_passwd -c /mosquitto/config/passwd fueragatos
